### PR TITLE
More improvements

### PR DESCRIPTION
**Pull request by bbatsov**
Here's one more batch of cleanup commits. I've removed quite a bit of redundant & unused code, which will make understanding the code easier for newcomers.

### CODE REVIEW

**Comment by punassuming** [comment]
I will have to CP some of these in. The syntax table and the chm opener are works in progress, so I don't want to completely clean them up yet.

**Comment by bbatsov** [comment]
As you wish - IMO it doesn't make sense to have incomplete/unused code as it's simply confusing (it took me quite a while to figure out what parts of the code did - if this code wasn't there my life would have been simpler). It's better to keep work-in-progress on separate branches instead of on master.

**Comment by punassuming** [comment]
True, I created separate branch to track that progress and added you as a collaborator if you are interested in helping out more.

**Comment by bbatsov** [comment]
Thanks! I hope I'll be able to help more. I've recently started using after a 10-year hiatus and I'm quite interested in learning more about AHK.

**Pull request merged**
